extends:
  - stylelint-config-standard-scss

rules:
  selector-id-pattern: null
  selector-class-pattern: null

  at-rule-empty-line-before: null
  no-descending-specificity: null

  scss/comment-no-empty: null
  scss/load-no-partial-leading-underscore: null
  scss/dollar-variable-empty-line-before: null
